In [2]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np

In [41]:
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [42]:
one_hot("Deepak is a data scientiest",100)

[26, 99, 22, 93, 33]

In [43]:
vocab_size=30
encoded_vector=[one_hot(i,vocab_size) for i in reviews]
encoded_vector

[[25, 24],
 [19, 10],
 [25, 9],
 [7, 11, 12],
 [27, 14, 26],
 [15, 24],
 [15, 14, 26],
 [9, 25],
 [9, 11],
 [28, 21]]

In [44]:
max_length_of_sentence=3
padded_revies=pad_sequences(encoded_vector,maxlen=max_length_of_sentence,padding='post')
padded_revies

array([[25, 24,  0],
       [19, 10,  0],
       [25,  9,  0],
       [ 7, 11, 12],
       [27, 14, 26],
       [15, 24,  0],
       [15, 14, 26],
       [ 9, 25,  0],
       [ 9, 11,  0],
       [28, 21,  0]], dtype=int32)

In [47]:
embed_vector_size=4
model=keras.models.Sequential([
    keras.layers.Embedding(input_dim=vocab_size,output_dim=embed_vector_size,input_length=max_length_of_sentence,name="Embedding"),
    keras.layers.Flatten(),
    keras.layers.Dense(1,activation="sigmoid")
])
model.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

In [48]:
x=padded_revies
y=sentiment

In [49]:
model.fit(x,y,epochs=50)

Epoch 1/50
1/1 [==============================] - 1s 642ms/step - loss: 0.6997 - accuracy: 0.4000
Epoch 2/50
1/1 [==============================] - 0s 11ms/step - loss: 0.6987 - accuracy: 0.4000
Epoch 3/50
1/1 [==============================] - 0s 10ms/step - loss: 0.6977 - accuracy: 0.4000
Epoch 4/50
1/1 [==============================] - 0s 10ms/step - loss: 0.6968 - accuracy: 0.4000
Epoch 5/50
1/1 [==============================] - 0s 9ms/step - loss: 0.6959 - accuracy: 0.5000
Epoch 6/50
1/1 [==============================] - 0s 11ms/step - loss: 0.6949 - accuracy: 0.5000
Epoch 7/50
1/1 [==============================] - 0s 10ms/step - loss: 0.6940 - accuracy: 0.5000
Epoch 8/50
1/1 [==============================] - 0s 11ms/step - loss: 0.6930 - accuracy: 0.5000
Epoch 9/50
1/1 [==============================] - 0s 13ms/step - loss: 0.6921 - accuracy: 0.5000
Epoch 10/50
1/1 [==============================] - 0s 21ms/step - loss: 0.6912 - accuracy: 0.5000
Epoch 11/50
1/1 [============

In [50]:
model.evaluate(x,y)

1/1 [==============================] - 0s 128ms/step - loss: 0.6505 - accuracy: 1.0000


[0.6505382657051086, 1.0]

In [52]:
weigths=model.get_layer("Embedding").get_weights()[0]

In [53]:
len(weigths)

30

In [57]:
weigths[25] #weigths for nice word

array([-0.01724034,  0.00725545, -0.0151552 , -0.09242281], dtype=float32)

In [58]:
weigths[24]#weigths for food word

array([-0.03509581,  0.00335222, -0.01501196,  0.05893331], dtype=float32)